### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/07-recipe-app-backend-aminmus#1]
@aminmus Please ping me back by closing this issue when it's done and ready for grading.

**Comment by aminmus** [comment]
@cicely-f Ready for grading.

**Comment by aminmus** [comment]
I forgot I still have to deploy this.

**Comment by aminmus** [comment]
Done and deployed to https://recipes.amin.nu.
Ready for grading.
@cicely-f
